<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pROJEKT_MIASI" nsURI="http://www.example.org/pROJEKT_MIASI"
    nsPrefix="pROJEKT_MIASI">
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForeignKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primarykeycontraint" eType="#//PrimaryKeyContraint"
        containment="true" eOpposite="#//PrimaryKeyContraint/column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignkeycontraint" lowerBound="1"
        eType="#//ForeignKeyContraint" containment="true" eOpposite="#//ForeignKeyContraint/column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" lowerBound="1" eType="#//Table"
        eOpposite="#//Table/column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryKeyContraint" eSuperTypes="#//Contraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
        eType="#//Column" eOpposite="#//Column/primarykeycontraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForeignKeyContraint" eSuperTypes="#//Contraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" eType="#//Column"
        eOpposite="#//Column/foreignkeycontraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primarykeycontraint" eType="#//PrimaryKeyContraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contraint" lowerBound="1"
        upperBound="-1" eType="#//Contraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" upperBound="-1"
        eType="#//Column" containment="true" eOpposite="#//Column/table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" upperBound="-1"
        eType="#//Table" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contraint" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
